### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by zappen999** [kodjevlar/kraken#2]
When i run kraken in production, I want to log everything, so I can monitor the application

**Comment by JoelRoxell** [comment]
Aye, start using this template m8:

```
When <situation>, I want to <motivation>, so I can <expected outcome>
```

**Comment by zappen999** [comment]
@JoelRoxell Fixed

**Comment by JoelRoxell** [comment]
How should a preferable `Log` object look?

**Comment by zappen999** [comment]
@JoelRoxell Log information is so application specific, so i think it will be difficult to define a structure for it. I'll be using Winston to starters. Basics:
- Levels (I'll be using npm levels: { error: 0, warn: 1, info: 2, verbose: 3, debug: 4, silly: 5 }
- Message - a string describing the log entry. Should be short and readable to humans.
- Metadata (optional) - Object with relevant metadata for the log entry

**Comment by zappen999** [comment]
Implemented winston as logging lib. Will implement specific transports when deciding logging server architecture.
